person/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^person/(?P<id>\d+)/$', 'spamstr.person.views.detail'),
    (r'^add/$', 'spamstr.person.views.add_or_edit', {'id': None}),
    (r'^edit/(?P<id>\d+)/$', 'spamstr.person.views.add_or_edit'),
    (r'^delete/(?P<id>\d+)/$', 'spamstr.person.views.delete'),
    (r'^$', 'spamstr.person.views.index'),
)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from urlsLocal import urlpatterns as newPatterns
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^spamstr/', include('spamstr.foo.urls')),

    # Uncomment the next line to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/(.*)', admin.site.root),
    (r'', include('spamstr.person.urls')),
#    (r'^$', 'spamstr.person.views.all')
)

urlpatterns += newPatterns

person/models.py
from django.db import models

class Person(models.Model):
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)
    company = models.CharField(max_length=200, blank=True)
    title = models.CharField(max_length=200)
    email = models.EmailField()
    url = models.URLField(blank=True, verify_exists=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = "people"    
    
    def __unicode__(self):
        return u"%s %s" % (self.first_name, self.last_name)
    
    def get_absolute_url(self):
        return "/person/%s/" % self.id
    
class PhoneNumber(models.Model):
    number = models.CharField(max_length=32)
    label = models.CharField(max_length=32)
    person = models.ForeignKey(Person)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = "phones"
    
    def __unicode__(self):
        return u"%s %s" % (self.label, self.number)

person/forms.py
from django.forms import ModelForm
from django.forms.formsets import formset_factory
from django.forms.models import inlineformset_factory
from django import forms
from spamstr.person.models import Person, PhoneNumber

LABEL_CHOICES = (
    ("home", "home"),
    ("mobile", "mobile"),
    ("work", "work"),
    ("fax", "fax")
)

class PersonForm(ModelForm):
    class Meta:
        model = Person

class PhoneNumberForm(forms.Form):
    number = forms.CharField()
    label = forms.ChoiceField(choices=LABEL_CHOICES)

PhoneNumberFormSet = inlineformset_factory(Person, PhoneNumber, fk_name='person', extra=2)
#PhoneNumberFormSet = formset_factory(PhoneNumberForm, extra=2)

person/views.py
from django.shortcuts import get_object_or_404, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.template import Context, loader, RequestContext
from spamstr.person.models import Person, PhoneNumber
from spamstr.person.forms import PersonForm, PhoneNumberFormSet

def index(request):
    people = Person.objects.all()
    template = loader.get_template('index.html')
    context = RequestContext(request)
    context.update({'page_name': 'index', 'people': people})
    return HttpResponse(template.render(context))
    # This does the exact same thing, but in one line.
    #return render_to_response("index.html", {'page_name': 'index', 'people': Person.objects.all()}, RequestContext(request))

def add_or_edit(request, id):
    if id is None:
        person = None
        page_name = "add"
    else:
        person = get_object_or_404(Person, id=id)
        page_name = "edit"
    if request.method == "GET":
        form = PersonForm(instance=person)
        phone_forms = PhoneNumberFormSet(instance=person)
    if request.method == "POST":
        form = PersonForm(request.POST, instance=person)
        phone_forms = PhoneNumberFormSet(request.POST, instance=person)
        if form.is_valid() and phone_forms.is_valid():
            person = form.save()
            phone_forms = PhoneNumberFormSet(request.POST, instance=person)
            phone_forms.is_valid()
            phone_forms.save()
            return HttpResponseRedirect('/person/%s/' % person.id)
    return render_to_response('add.html', {'page_name': page_name, 'form': form, 'phone_forms': phone_forms, 'person': person}, RequestContext(request))

def delete(request, id):
    person = Person.objects.get(id=id)
    person.delete()
    return HttpResponseRedirect('/')

def detail(request, id):
    person = Person.objects.get(id=id)
    return render_to_response('detail.html', {'page_name': 'detail','person': person}, RequestContext(request))

person/templates/add.html
{% extends "base.html" %}

{% block content %}
<h1>New person</h1>

<form method="POST" action=".">
	{{ form.as_p }}
	{{ phone_forms.management_form }}
	{% for form in phone_forms.forms %}
	<hr/>
	Phone # {{ forloop.counter }}
		{{ form.as_p }}
	{% endfor %}
	<input type="submit" value="{{ page_name }} Person"/>
</form>

{% endblock %}

person/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

  <head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <title>{{ page_name }} | Spamstr (Django edition)</title>
	<link rel="stylesheet" href="{{ MEDIA_URL }}stylesheets/default.css" type="text/css" media="screen">
  </head>

  <body>
    <div id="container">

      <div id="header">
        <h1>Spamstr</h1>

        <div id="nav" class="clearfix">
          <ul>
            <li><a href="/" {% ifequal page_name "index" %} class="current"{% endifequal %}>List People</a></li>
            <li><a href="/add/" {% ifequal page_name "add" %} class="current"{% endifequal %}>Add a Person</a></li>
			{% ifequal page_name "edit" %}
				<li><a href="/person/{{ person.id }}/" class="current">Editing {{ person }}</a></li>
			{% endifequal %}
			{% ifequal page_name "detail" %}
				<li><a href="/person/{{ person.id }}/" class="current">{{ person }}</a></li>
			{% endifequal %}
			
          </ul>
        </div>
      </div>

      <div id="content">
		{% block content %}{% endblock %}
      </div>
	<div id="footer"></div>
    </div>
  </body>
</html>

person/templates/detail.html
{% extends "base.html" %}

{% block content %}
	{% include "includes/person.html" %}
{% endblock %}

person/templates/includes/person.html
{% load gravatar %}
<div class="person clearfix">
  <h3 class="name"><a href="{{ person.get_absolute_url }}">{{ person }}</a></h3>

  <div class="avatar">
    <p><img src="{% gravatar_for_email person.email %}"/></p>
    <p><a href="/edit/{{ person.id }}/">edit</a> | <a href="/delete/{{ person.id }}/">delete</a></p>
  </div>

  <div class="information">

    <p class="title-and-company">{{ person.title}} at {{ person.company }}</p>
    <p class="emails">{{ person.email }}</p>
	
	{% if person.phonenumber_set.all %}
		<ul class="phones">
		{% for phoneNumber in person.phonenumber_set.all %}
			<li>{{ phoneNumber.number }} ({{ phoneNumber.label }})</li>
		{% endfor %}
		</ul>
	{% endif %}
  </div>

  <div class="timestamp">
    <p>Created on {{ person.created_at|date:"F d, Y" }}</p>
  </div>
</div>

person/templates/index.html
{% extends "base.html" %}

{% block content %}
		{% for person in people %}
			{% include "includes/person.html" %}
		{% endfor %}
{% endblock %}